# Generated by Django 3.2.9 on 2022-06-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.CharField(default=None, max_length=100, verbose_name='Ингриденты'),
            preserve_default=False,
        ),
    ]
